GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repli'@'localhost' IDENTIFIED BY 'mYpaS$word';

STOP SLAVE;
RESET SLAVE ALL;

CHANGE MASTER TO
MASTER_HOST='localhost',
MASTER_USER='repli',
MASTER_PASSWORD='mYpaS$word',
MASTER_USE_GTID=current_pos;

START SLAVE;
